# # # Use the official Node.js 12 image.
# # # https://hub.docker.com/_/node
# # FROM node:12

# # # Create and change to the app directory.
# # WORKDIR /usr/src/app
# # # Copy application dependency manifests to the container image.
# # # A wildcard is used to ensure both package.json AND package-lock.json are copied.
# # # Copying this separately prevents re-running npm install on every code change.
# # COPY package*.json ./
# # # Install production dependencies.
# # RUN npm install --only=production
# # # Copy local code to the container image.
# # FROM redis
# # COPY redis.conf /usr/local/etc/redis/redis.conf

# # COPY . .
# # EXPOSE 8080
# # # Run the web service on container startup.
# # CMD [ "node", "server.js" ]
# # ENTRYPOINT [ "redis-server"]




# FROM node:carbon

# RUN wget http://download.redis.io/redis-stable.tar.gz && \
#     tar xvzf redis-stable.tar.gz && \
#     cd redis-stable && \
#     make && \
#     mv src/redis-server /usr/bin/ && \
#     cd .. && \
#     rm -r redis-stable && \
#     npm install -g concurrently   

# EXPOSE 6379

# WORKDIR /app

# COPY package.json /app

# RUN npm install

# COPY . /app

# EXPOSE 8080

# EXPOSE 6379

# CMD concurrently "/usr/bin/redis-server --bind '0.0.0.0'" "sleep 5s; node /app/src/server.js"
