version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment: :
      DATABASE_URL: redis://redis:6379
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    
      