version: '3'
services:
  myapp:
    build: .  
    ports:
     - "8080:8080"
    depends_on:
     - redis:redis
  redis:
    image: "redis:alpine"
    version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
  redis:
    image: redis
    ports:
      - "8001:5432"